version: '2'

networks:
  crappo:
    driver: bridge
volumes:
  etcd:
    external: true
    driver: 'null'
services:
  data:
    image: busybox
    network_mode: none
    volumes:
    - /data
    command:
    - /bin/true
    labels:
      io.rancher.container.start_once: 'true'
  etcd:
    image: rancher/etcd:v2.3.7-11
    environment:
      BACKUP_PERIOD: 15m0s
      BACKUP_RETENTION: 24h
      EMBEDDED_BACKUPS: 'true'
      RANCHER_DEBUG: 'true'
    volumes:
    - etcd:/pdata
    - /dockervols/etcd/backups:/data-backup
    volumes_from:
    - data
    labels:
      io.rancher.sidekicks: data
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.affinity:host_label_soft: etcd=true
    networks:
      - crappo