.catalog:
  name: "Apache"
  version: "1.0.0"
  description: ""
  questions:
    - variable: "WP_PASSWORD"
      label: "Mysql database password"
      required: true
      default: "pAssW0rd"
      type: "string"
    - variable: "SERVICE_PORT"
      label: "Service port"
      required: true
      default: 80
      type: "int"
    - variable: "APACHE_REPLICAS"
      label: "Apache Replicas"
      required: true
      default: 1
      type: "int"
    - variable: "MYSQL_REPLICAS"
      label: "MySQL Replicas"
      required: true
      default: 1
      type: "int"
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "Percona root pass"
      required: true
      default: "lh53jh53jkh"
      type: "string"
    - variable: "MYSQL_ALLOW_EMPTY_PASSWORD"
      label: "Allow empty passwords?"
      required: true
      default: "no"
      type: "string"
#    - variable: "MYSQL_RANDOM_ROOT_PASSWORD"
#      label: "Set a random root password?"
#      required: true
#      default: "no"
#      type: "string"
    - variable: "CLUSTER_NAME"
      label: "Set cluster name"
      required: true
      default: "cluster1"
      type: "string"
    - variable: "DISCOVERY_SERVICE"
      label: "Discovery service"
      required: false
      default: ""
      type: "string"
    - variable: "XTRABACKUP_PASSWORD"
      label: "xtrabackup password"
      required: true
      default: "Theistare"
      type: "string"
    - variable: "MYSQL_PROXY_USER"
      label: "Mysql proxy user"
      required: true
      default: "proxyuser"
      type: "string"
    - variable: "MYSQL_PROXY_PASSWORD"
      label: "Mysql proxy user"
      required: true
      default: "s3cret"
      type: "string"