# A pod is a group of containers that are scheduled onto the same host.
# Pods serve as units of scheduling, deployment, and horizontal scaling/replication.
# Pods share fate, and share some resources, such as storage volumes and IP addresses.
# https://kubernetes.io/docs/user-guide/pods/multi-container/

apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    app: apache
spec:
  containers: # containers that make up this pod
    - name: apache
      image: httpd:latest
      ports:
        - containerPort: 80
    - name: database
      image: prodigymike/percona-xtradb-cluster
      ports:
        - containerPort: 3306