apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: apache
    spec:
#      volumes:
#      - name: secret-volume
#        secret:
#          secretName: apachesecret
#      - name: configmap-volume
#        configMap:
#          name: apacheconfigmap
      containers:
      - name: apachehttps
        image: httpd:latest
#        command: ["/home/auto-reload-nginx.sh"]
        # ports in the container
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
#        volumeMounts:
#        - mountPath: /etc/nginx/ssl
#          name: secret-volume
#        - mountPath: /etc/nginx/conf.d
#          name: configmap-volume