# This is a combined file
# It appears this is the preferred way to deploy multiple items
# Further, it appears I need to remove the deployment file and just use others

# https://kubernetes.io/docs/user-guide/services
apiVersion: v1
kind: Service
# Set data for this service
metadata:
  name: apache-svc
  labels:
    app: apache
spec:
  # Optional. NodePort/LoadBalancer. NodePort = Each node proxies that port. Set port via ports.nodePort. LoadBalancer = What you think it is.
  type: LoadBalancer
  # Ports to map. Port is the service port to expose on the cluster IP.
  # targetPort is the port to target on the pods that are part of this service
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  # The label key:value pair that defines the pods to target
  selector:
    app: apache
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: apache
#  labels:
#    app: apache
#spec:
#  containers: # containers that make up this pod. deployment features?
#    - name: apache
#      image: httpd:latest
#      ports:
#        - containerPort: 80
#    - name: database
#      image: prodigymike/percona-xtradb-cluster
#      ports:
#        - containerPort: 3306
#---
apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-rc
spec:
#  replicas: 2
  replicas: ${APACHE_REPLICAS}
  template:
    metadata:
      labels:
        app: apache
    spec:
#      volumes:
#      - name: secret-volume
#        secret:
#          secretName: apachesecret
#      - name: configmap-volume
#        configMap:
#          name: apacheconfigmap
      containers:
      - name: apache
        image: httpd:latest
#        command: ["/home/auto-reload-nginx.sh"]
        # ports in the container
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
#        volumeMounts:
#        - mountPath: /etc/nginx/ssl
#          name: secret-volume
#        - mountPath: /etc/nginx/conf.d
#          name: configmap-volume