.catalog:
  name: "Percona XtraDB Cluster (No ProxySQL)"
  version: "1.0.0"
  description: ""
  questions:
    - variable: "REPLICAS"
      label: "Number of replicas"
      required: true
      default: "1"
      type: "int"
    - variable: "MYSQL_ROOT_PASSWORD"
      label: "Percona root pass"
      required: true
      default: "lh53jh53jkh"
      type: "string"
#    - variable: "MYSQL_ALLOW_EMPTY_PASSWORD"
#      label: "Allow empty passwords?"
#      required: true
#      default: "0"
#      type: "string"
#    - variable: "MYSQL_RANDOM_ROOT_PASSWORD"
#      label: "Set a random root password?"
#      required: true
#      default: "no"
#      type: "string"
    - variable: "CLUSTER_NAME"
      label: "Set cluster name"
      required: true
      default: "cluster1"
      type: "string"
    - variable: "DISCOVERY_SERVICE"
      label: "Discovery service. Cluster IP resolvable via service name using Rancher/Kubernetes DNS."
      required: false
      default: "etcd:4001"
      type: "string"
#    - variable: "SERVICE_HOST_PREFIX"
#      label: "ETCD Service name? UPPERCASE ONLY!"
#      required: true
#      default: "ETCD"
#      type: "string"
    - variable: "XTRABACKUP_PASSWORD"
      label: "xtrabackup password"
      required: true
      default: "Theistare"
      type: "string"
#    - variable: "SERVICE_NAME"
#      label: "Service name"
#      required: true
#      default: "mysql"
#      type: "string"