apiVersion: v1
kind: Pod
metadata:
  name: pxc-deployment
spec:

  containers:
  - name: percona-server
#    image: percona/percona-xtradb-cluster:5.7
#    image: percona/percona-xtradb-cluster:5.7.16
    image: prodigymike/percona-xtradb-cluster-vip
    ports:
    - containerPort: 3306
    - containerPort: 4567
    - containerPort: 4568
    env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "1"
#        - name: MYSQL_ROOT_PASSWORD
#          value: "${MYSQL_ROOT_PASSWORD}"
    - name: DISCOVERY_SERVICE
      value: "${DISCOVERY_SERVICE}"
    - name: CLUSTER_NAME
      value: "${CLUSTER_NAME}"
    - name: XTRABACKUP_PASSWORD
      value: "${XTRABACKUP_PASSWORD}"
#        - name: SERVICE_NAME
#          value: "${SERVICE_NAME}"
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    emptyDir: {}