apiVersion: v1
kind: ReplicationController
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  replicas: 1
  selector:
    name: ubuntu
  template:
    metadata:
      name: ubuntu
      labels:
        name: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          stdin: true # CRITICAL! Won't boot without this!
          tty: true # CRITICAL! Won't boot without this!